### PR TITLE
Fix #17: Modify storage types to accept synchronous results

### LINKED ISSUE #17: Typescript incompatible type when using window.localstorage as storage
Issue: Typescript types check fails when using localstorage as storage for persistCache using the following example:
```ts
const cache = new InMemoryCache();
persistCache({
  cache, 
  storage: localStorage
});
```

error:
```ts
[ts]
Argument of type '{ cache: InMemoryCache; storage: Storage; }' is not assignable to parameter of type 'ApolloPersistOptions<NormalizedCacheObject>'.
  Types of property 'storage' are incompatible.
    Type 'Storage' is not assignable to type 'PersistentStorage<PersistedData<NormalizedCacheObject>>'.
      Types of property 'getItem' are incompatible.
        Type '(key: string) => string | null' is not assignable to type '(key: string) => Promise<PersistedData<NormalizedCacheObject>>'.
          Type 'string | null' is not assignable to type 'Promise<PersistedData<NormalizedCacheObject>>'.
            Type 'null' is not assignable to type 'Promise<PersistedData<NormalizedCacheObject>>'.
var localStorage: Storage
```
Typescript version: 2.6.2
tsconfig.json file inclues ```
"lib": ["esnext", "dom"],```

EDIT: Typescript fails because localStorage functions don't return Promises, while the PersistentStorage type functions return Promises.

### PR DESCRIPTION
**Pull request by jamesreggio**
`localStorage` is synchronous, so we don't always receive a promise from the storage provider. This PR massages the types to support this common scenario.

The `awaits` have been added to the `Storage` module in order to guarantee is returned from those methods regardless of whether the underlying storage provider returns a function. This is a convenience to prevent the proliferation of `Promise<T> | T` union types.

### CODE REVIEW

File: src/Storage.ts [hunk 1]
```diff
@@ -15,16 +15,16 @@ export default class Storage<T> {
     this.key = key;
   }
 
-  read(): Promise<PersistedData<T>> {
-    return this.storage.getItem(this.key);
+  async read(): Promise<PersistedData<T>> {
+    return await this.storage.getItem(this.key);
```
Comment (peggyrayzis) [inline src/Storage.ts]: I think it's enough to just `return` here since `async` functions wrap a `Promise.resolve()` over the returned value.

Comment (jamesreggio) [reply src/Storage.ts]: Ah, very good point! Will fix.

**Comment by peggyrayzis** [comment]
@jamesreggio Just released this change in v0.1.1 👍
